import CustomSubsidyFormFieldsObjectiveTableEditComponent from './edit';

export default class CustomSubsidyFormFieldsObjectiveTableShowComponent extends CustomSubsidyFormFieldsObjectiveTableEditComponent {}
