import CustomSubsidyFormFieldsEstimatedCostTableEditComponent from './edit';

export default class CustomSubsidyFormFieldsEstimatedCostTableShowComponent extends CustomSubsidyFormFieldsEstimatedCostTableEditComponent {

}
