import CustomSubsidyFormFieldsPlanLivingTogetherTableEditComponent from "./edit";

export default class CustomSubsidyFormFieldsPlanLivingTogetherTableShowComponent extends CustomSubsidyFormFieldsPlanLivingTogetherTableEditComponent {
}
