steps:
  install:
    image: node:22
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
when:
  event: tag
  ref: refs/tags/v*
