steps:
  install:
    image: danlynn/ember-cli:6.5.0-node_22.16
    commands:
      - npm ci
  test:
    image: danlynn/ember-cli:6.5.0-node_22.16
    commands:
      - npx ember try:one embroider-optimized
when:
  event: pull_request

depends_on:
  - test-pr
