import CustomSubsidyFormFieldsClimateSubsidyCostsTableEditComponent from './edit';

export default class CustomSubsidyFormFieldsClimateSubsidyCostsTableShowComponent extends CustomSubsidyFormFieldsClimateSubsidyCostsTableEditComponent {

}
